### ISSUE TITLE
Program Page Incorporate Assets

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#140]
Get and incorporate assets.

We are keeping it to only 4 topics.

- [x] Update topic cards
- [x] Incorporate assets from UX

**Comment by douglaschan32167** [comment]
Assigning to @jessewoo . He can do the cards and then move it back to blocked once he's done.

**Comment by lillyglin** [comment]
@jessewoo Latest copywriting has been updated here: https://3.basecamp.com/4474129/buckets/16925967/documents/2735700785

**Comment by jessewoo** [comment]
@lillyglin and @douglaschan32167 - pretty much done. need assets. 

wondering, when using assets...do we need to purchase the assets?

**Comment by lillyglin** [comment]
@jessewoo UX & D are gonna get those for us. The assets are free for commercial use. :D

**Comment by jessewoo** [comment]
Cool, please have the UX & D photoshop to a set dimension - I just did it to 650px width by 200px because if you go with a 2 column layout for the container 1684px, it's about right to have 650px for each image. I just threw it into Photoshop and cropped all 4 images to bring uniformity. Also, save as web, compress it please. 

![image](https://user-images.githubusercontent.com/12104578/84583016-82df3a80-ada8-11ea-9e9a-634aab8a6fae.png)

**Comment by lillyglin** [comment]
@jessewoo Here ya go: https://3.basecamp.com/4474129/buckets/16925967/vaults/2758559772

**Comment by lillyglin** [comment]
@jessewoo Moved this over from blocked to in progress.

**Comment by jessewoo** [comment]
![image](https://user-images.githubusercontent.com/12104578/85100334-c1b02e80-b1b4-11ea-8688-9ea0ab79b916.png)

**Comment by lillyglin** [comment]
@jessewoo 🇺🇸
