### ISSUE TITLE
Swap topic filter with search filter in /blog-list

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#255]
Imo, the topic filter would be more useful. I'm not sure exactly what I would search for when I first look at the /blog-list page. Therefore, I think it'd be better for that to be on the left where our attention first goes to. 
<img width="2659" alt="Screen Shot 2020-06-20 at 11 16 01 AM" src="https://user-images.githubusercontent.com/66575722/85208716-73e81300-b2e7-11ea-9aae-e924b1c9242e.png">

**Comment by vickyadebona** [comment]
@iksoosong I agree, I think the topic dropdown should go to the left. From a UI perspective, it also looks misaligned when right-aligned on mobile. Should we change this ticket to realign the topics dropdown? I'm not quite sure if we should remove the search bar since we still want to ability for users to search for a specific article, but we can at least put the dropdown below the search bar.

**Comment by vickyadebona** [comment]
Nevermind, realized the ui was fixed for the search bar and dropdown to stack on mobile.
