### ISSUE TITLE
Blog Article page feels empty

### ISSUE THREAD

**Issue by JonSEng** [International-Mentorship-ISMP/ismp#307]
**Description**

- [ ] I've added the proper component `comp/*` label + other labels
- [ ] I've added any context to where the decision was made (Basecamp links...etc.)

**Comment by vickyadebona** [comment]
@JonSEng what do you think will help make the blog page feel less empty?

Do you think it needs something on the sides since there's a thick horizontal margin on the blog article itself? I guess we're all used to there being random ads on the margins when we read articles from other websites. Should we decrease the blog horizontal margins?

The recommended articles section that will go at the bottom of the article page should help fill in some space on the bottom at least.

Maybe we can also take a look at the [Zine](https://zine.gracepointonline.org/) articles for inspiration?

**Comment by vickyadebona** [comment]
@JonSEng is this something that we still want to fix, or should this be pushed to v2?

**Comment by JonSEng** [comment]
Hi @vickyadebona sorry I missed this. I think it can be cleanup for post launch.
Thanks!
