### ISSUE TITLE
Homepage: Featured Blogposts Repeated Images

### ISSUE THREAD

**Issue by lillyglin** [International-Mentorship-ISMP/ismp#391]
https://3.basecamp.com/4474129/buckets/16925967/todos/2842530276

On the main page, two out of the three blogposts are the same.
Can we swap one out?

**Comment by vickyadebona** [comment]
It seems that the '3 Tips for Managing Loneliness' and 'A Short Guide on Where to live in College' are duplicated in our blog DB. @douglaschan32167 I'll need some help removing those (or you can show me how to do it myself). Maybe we can remove the ones that don't have any topics associated to them (because their duplicates have the 'Transitioning to America topic).

**Comment by JonSEng** [comment]
This seems to be done per @dougchansolute https://3.basecamp.com/4474129/buckets/16925967/todos/2842530276
